
server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: Comedian
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 120000
        ok-http:
          read-timeout: 120000
