server:
  port: 9091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: Orchestrator
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 120000
        ok-http:
          read-timeout: 120000

deepl:
  authKey: <insert apikey>