server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: LLM
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 120000
        ok-http:
          read-timeout: 120000


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui